### ISSUE TITLE
Directives wrapper parse error

### ISSUE THREAD

**Issue by xiaocang** [openresty/lemplate#6]
when I use `WRAPPER` in tt2 file, there is an error in output lua file.

Reproduce
---
### `t.tt2` content:

``` tt2
[% BLOCK wrapper_bug %]
[% content %]
[% END %]

[% WRAPPER wrapper_bug %]
    test
[% END %]
```

### execute `lemplate` in bash
``` bash
$ lemplate --compile t.tt2 > template.lua
```
luac output
---
    luac5.1: template.lua:149: unexpected symbol near '/'

149 lines context
---

``` lua
   146  i = i + 1 output[i] = '\n\n'
   147  -- line 7 "t.tt2"
   148
   149  // WRAPPER
   150  i = i + 1 output[i] = (function() {
   151      var output = '';
   152  i = i + 1 output[i] = '\n    test\n';
   153      return context.include('wrapper_bug', { 'content': output });
   154  })();
```

**Comment by agentzh** [comment]
@xiaocang I'm afraid `WRAPPER` is not really implemented yet.

**Comment by xiaocang** [comment]
OK, thx. 
I will use another directives to avoid this error.
Cloud you please update the README doc file to let others know about it.

**Comment by agentzh** [comment]
@xiaocang Updated docs. Thanks!
